### PR TITLE
async S3 HTTP with botornado

### PR DESCRIPTION
**Pull request by pda**
Summary: [thumbor](https://github.com/thumbor/thumbor) runs on [tornado](http://www.tornadoweb.org/en/stable/) which is async, but [thumbor_aws](https://github.com/willtrking/thumbor_aws) uses [boto](https://github.com/boto/boto) for HTTP to S3 which is blocking, causing awful performance. This patch uses [botornado](https://github.com/yyuu/botornado), a tornado async partial port of boto, to make S3 requests non-blocking.

Test material at https://gist.github.com/pda/5dcf54410b696072fcbd

---

In production we have an ELB load balancer in front of two EC2 instances each running thumbor + thumbor_aws inside a docker container. We had reports of blank images, and then hints that they were HTTP 503 errors, but it wasn't reproducible. Our logs shows that the load balancer frequently marked the instances as unhealthy, meaning they've failed to respond to health checks. The thumbor processes had been up and running for many days, and had no suspicious log entries.

I suspected that something was blocking inside the thumbor event loop, and narrowed it down to boto in thumbor_aws.

Using a controllably slow backend behind thumbor_aws, I was able to demonstrate the single-concurrency of boto by showing slow requests blocking fast requests:

```
$ ./race.rb http://localhost:8888/unsafe/sleep/{10,1000,100,10000,500}

dispatching http://localhost:8888/unsafe/sleep/10
dispatching http://localhost:8888/unsafe/sleep/1000
dispatching http://localhost:8888/unsafe/sleep/100
dispatching http://localhost:8888/unsafe/sleep/10000
dispatching http://localhost:8888/unsafe/sleep/500
78 ms for http://localhost:8888/unsafe/sleep/10
2030 ms for http://localhost:8888/unsafe/sleep/1000
2168 ms for http://localhost:8888/unsafe/sleep/100
22108 ms for http://localhost:8888/unsafe/sleep/10000
23051 ms for http://localhost:8888/unsafe/sleep/500
```

(The double times in the benchmarks are due to the test server sleeping `n milliseconds` for both the HEAD and GET requests. Perhaps that HEAD request should be eliminated from thumbor_aws, but that's a separate issue).

Note that the responses are serialized into the order they arrived, and that the time is roughly cumulative — the final request which should have taken 1,000ms took 23,000ms.

Switching `s3_loader.py` from `boto` to `botornado` fixes that:

```
$ ./race.rb http://localhost:8888/unsafe/sleep/{10,1000,100,10000,500}

dispatching http://localhost:8888/unsafe/sleep/10
dispatching http://localhost:8888/unsafe/sleep/1000
dispatching http://localhost:8888/unsafe/sleep/100
dispatching http://localhost:8888/unsafe/sleep/10000
dispatching http://localhost:8888/unsafe/sleep/500
89 ms for http://localhost:8888/unsafe/sleep/10
228 ms for http://localhost:8888/unsafe/sleep/100
1024 ms for http://localhost:8888/unsafe/sleep/500
2028 ms for http://localhost:8888/unsafe/sleep/1000
20024 ms for http://localhost:8888/unsafe/sleep/10000
```

---

This fix uses botornado to do async HTTP requests to S3 in a way that fits the tornado event loop model, without blocking other requests.

I've only applied it to the `loaders` module, as that's the only component that we're using. It should probably also be applied to the `storages` and `result_storages` modules. Perhaps we can ship this fix first, though?

### CODE REVIEW

**Comment by fluke** [comment]
I think this needs to be implemented. Could you merge this in.

**Comment by pda** [comment]
I discovered that this wasn't loading AWS credentials from the environment in the expected way.
In the end, I wrote https://github.com/99designs/thumbor_botornado which has [a very simple botornado loader](https://github.com/99designs/thumbor_botornado/blob/master/thumbor_botornado/s3_loader.py) and also a [loader which can sit in front of that to handle non-S3 URLs separately](https://github.com/99designs/thumbor_botornado/blob/master/thumbor_botornado/s3_http_loader.py). 99designs.com has since been using it to serve millions of images.

So — I'm not sure about this PR, it might need more work, but I'm not using it anymore.

**Comment by fluke** [comment]
@pda Well as of now I'm simply using the HTTP loader with URL signing. As I was coming across this issue #19 with multiple buckets. What are the benefits of using the AWS bucket method?

**Comment by pda** [comment]
@kartikluke If the original images are in a public readable S3 bucket, then the HTTP loader is perfect. But if the original images aren't public readable, then S3 credentials are required… as far as I know the HTTP loader doesn't know how to do that…?

**Comment by fluke** [comment]
Ah that's correct. Sorry. Got confused.

**Comment by pda** [comment]
Closing this; as I mentioned I wrote https://github.com/99designs/thumbor_botornado which we're using. Feel free to use the code from this PR or that `99designs/thumbor_botornado` repo, though.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcTx6e8MOH65DvWGyFVqW6UUojDVKIn5676vrBTssa2t2NtsInaQw6-2BbmoXKyfEdOs7o9wB3Zf9aGWl1KJNlOTpC6iUSnUOOyiWd6LqUefw3Aonjz2BnbYU0CK3UKlxfnOHC3okrKZaUfJV-2BPaOiY6RKoIaLCYqRDJRqbyBtHJya-2F3TocLbwhwpI3IfTRPWqTH8phOymxtV8AXNmF61q-2FgtkT6Edhm3EkGzuR71nUCx4ICBuuxpyB5gpV3dLMRT8qObdEiFGWQ2QMTYuOKi-2FlkvnC8-2FmEvFbxzp0fRs1I34cozbvKYSVxQJFPxMzfFj550MIRNzB5cPlPjpVnJt2LhPUsrrKlYd-2BzNAeDfmjK9xLS and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcTx6e8MOH65DvWGyFVqW6UUojDVKIn5676vrBTssa2t2NtsInaQw6-2BbmoXKyfEdOs7o9wB3Zf9aGWl1KJNlOTpC6iUSnUOOyiWd6LqUefw3Aonjz2BnbYU0CK3UKlxfnOHC3okrKZaUfJV-2BPaOiY6RKoIaLCYqRDJRqbyBtHJya-2FQuJJM6-2BG-2BLV-2BJ-2BZOs86bV8jwcNPu1xCFodsSVujpcl48IuW9A3CpCe9J3GJtKg8fDnl2EjnT3Xp3amQH8I6MvXOPxeFZJcFhXkQodOKIDLkIbS2YvwgE-2B9d-2FV4TgdZJNei0Ueri7ZZn97auJq2M-2B5o7Ql9aIZXAxEaECPaSxwMfL4epspA99xj-2FI94NCf6WR

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcTx6e8MOH65DvWGyFVqW6UUojDVKIn5676vrBTssa2t2NtsInaQw6-2BbmoXKyfEdOs7o9wB3Zf9aGWl1KJNlOTpC6iUSnUOOyiWd6LqUefw3Aonjz2BnbYU0CK3UKlxfnOGfYC8hR4S10zBwWX-2BkDJo0e3sMriwSr-2BsR2Gu7-2Bj1Q0Gg-2FeB8Q4uVTtKAuqy7OowYLdPlA3Bb-2BQ1BJvt-2BxJeGEp0aj0oqrJag-2Bfd-2FJgXhJcC8uZZSW9QmUh0igR5948uurSUnbFcLHM2IssdtQwuuyLLCxO5yRZvAR0WwZypq2-2BG3Te-2Bc8yIpoKY13jVZXM2LC92L9eIxY3gf-2BskGmO9weLE-2FLtrXwVjW4wFrcTn86i and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcTx6e8MOH65DvWGyFVqW6UUojDVKIn5676vrBTssa2t2NtsInaQw6-2BbmoXKyfEdOs7o9wB3Zf9aGWl1KJNlOTpC6iUSnUOOyiWd6LqUefw3Aonjz2BnbYU0CK3UKlxfnOGfYC8hR4S10zBwWX-2BkDJo0e3sMriwSr-2BsR2Gu7-2Bj1Q02WOvsm2MWF6iqnTWSeDexQlUbm1MPMFaUtmZRlEcnr58wUjuTs7UVcp5rWEggumWowd1ky0YfESoRlom42uWYUipEpGXeRgPk-2Bt6v5Qwn88KMiV-2FSye4jE3ULrhzrMOVuSsErQmx5coLiBZ8fMi0DruxZDt4mBmbGcuM5gFh8hqYZFkK2F8Wtxj-2BFUZgrj5L

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.

**Pull request closed without merging**
